### ISSUE TITLE
go get fails currently

### ISSUE THREAD

**Issue by EinPinsel** [jesseduffield/lazydocker#13]
While trying to install lazydocker, it fails with the following error: "undefined: strings.ReplaceAll" in 
https://github.com/jesseduffield/lazydocker/blob/51d9b14ab5549a76fc159bbe0ac3e5d387a8ee00/pkg/commands/image.go#L71

**Comment by mjarkk** [comment]
What is your go version?

**Comment by jesseduffield** [comment]
@EinPinsel apologies, it turns out that function is only available in go1.12 onwards. I added to the readme that you need that version. I'm not really averse to using a different function than strings.ReplaceAll if it's enough of a hassle for people who are on old go versions. What are your thoughts?

**Comment by EinPinsel** [comment]
You got me there - it was `go version go1.10.4 linux/amd64`. With 1.12 it works. I'm still finding my way around go - and that you can't just get it from the default repo is a bit of missing comfort.

**Comment by jesseduffield** [comment]
@EinPinsel fair enough. I think I'll close this issue and if we get another person who gets stumped on this I'll go and replace the function with something else :)
