### ISSUE TITLE
App crashes when clicking on "project"

### ISSUE THREAD

**Issue by bartekczyz** [jesseduffield/lazydocker#140]
**Describe the bug**
Clicking on "project" - top left section, closes the app with an error

**To Reproduce**
1. Click "project"

**Expected behaviour**
App should not crash?

**Desktop (please complete the following information):**
 - OS: Mac
 - Lazydocker Version 0.6.3

**EDIT** turns out "Project" might be also "Status". I don't know how to change the language

**Comment by djumpen** [comment]
Same on ubuntu host. RabbitMQ crashes sometimes when selecting container in lazydocker

**Comment by Ziktofel** [comment]
Happens too on Linux Mint 19.1 64-bit:
![Snímek obrazovky pořízený 2019-07-31 19-51-58](https://user-images.githubusercontent.com/3447808/62235266-d7660b00-b3cc-11e9-9788-d957c3ce32bd.png)

**Comment by pvande** [comment]
@Ziktofel Could you confirm – if you *do* have a `docker-compose.yml` file, you don't see the crash?  Do you see the crash if you navigate to the "About" tab?

From what I can tell, this stems from [this commit](https://github.com/jesseduffield/lazydocker/commit/1f9f82601b317e4fc32ad4a350e829637c9f5c52), where a function reference was added to the `CustomCommand` struct.  Despite the hints to the contrary, Go functions cannot be serialized to or deserialized from YAML, and the "About" tab tries to serialize the entire configuration to YAML as a part of its rendering.

@jesseduffield It seems like Bulk Commands are either not capable of being user-configured, or they're not capable of running Go code.  I'd be happy to take a stab at this, if you'd let me know which way you'd like to go.

**Comment by jesseduffield** [comment]
Interesting. For context, that internalFunction key isn't meant to be used by the user, it's just there so that we can concatenate internal commands which indeed do hook into go code with external user-defined commands that run things on the command line. 

If this issue is indeed due to us trying to encode/decode that stuff, it seems like we need to just express that we don't want that field being serialized at all (It was silly of me to give it a yaml key name when I didn't intend for it to actually be encoded into yaml). I wonder if there is some struct field tag we can use to express that (if you want to investigate @pvande feel free!)

**Comment by Ziktofel** [comment]
@pvande If I execute lazydocker from the directory containing docker-compose.yml, I don't observe crash after clicking on the project name but, however, when I navigate to "About" tab, it crashes anyway

**Comment by dawidd6** [comment]
@Ziktofel @bartekczyz should be fixed in `master` now.
