### ISSUE TITLE
lazydocker is spawning orphaned docker logs processes

### ISSUE THREAD

**Issue by keigel2001** [jesseduffield/lazydocker#147]
**Describe the bug**
Everytime I open lazydocker, it's spwaning new processes of `docker logs`, which never get closed when closing lazydocker. After every usage of lazydocker, there's more processes.

**To Reproduce**
I'm using the binary release v0.6.4 of lazydocker and have one docker container running.
Open lazydocker and close it.
Then check f.e. with `ps aux | grep logs` for `docker logs`-processes.

**Expected behaviour**
`docker logs` processes get closed, after closing lazydocker.

**Screenshots**
![image](https://user-images.githubusercontent.com/9857738/62442595-aaad4d00-b758-11e9-8b96-ea09536a9418.png)

**Desktop (please complete the following information):**
 - OS: `Linux debian 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux`
also happenes with debian stretch (`Linux debian 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux`)
 - Docker: `19.03.1, build 74b1e89`
 - Lazydocker Version v0.6.4 (Binary Release)

**Comment by glvr182** [comment]
In container_panel.go we handle view logs like this:
```go
func (gui *Gui) handleContainerViewLogs(g *gocui.Gui, v *gocui.View) error {
	container, err := gui.getSelectedContainer()
	if err != nil {
		return nil
	}

	c, err := container.ViewLogs()
	if err != nil {
		return gui.createErrorPanel(gui.g, err.Error())
	}

	gui.SubProcess = c
	return gui.Errors.ErrSubProcess
}
```
As we can see this calls container.ViewLogs(), which returns a cmd:
```go
// ViewLogs attaches to a subprocess viewing the container's logs
func (c *Container) ViewLogs() (*exec.Cmd, error) {
	templateString := c.OSCommand.Config.UserConfig.CommandTemplates.ViewContainerLogs
	command := utils.ApplyTemplate(
		templateString,
		c.DockerCommand.NewCommandObject(CommandObject{Container: c}),
	)

	cmd := c.OSCommand.ExecutableFromString(command)
	c.OSCommand.PrepareForChildren(cmd)

	return cmd, nil
}
```
Then the returned command is used in a subprocess and run like this:
```go
func (gui *Gui) runCommand() error {
       //... cpde

	c := make(chan os.Signal, 1)

	go func() {
		signal.Notify(c, os.Interrupt)
		<-c
		signal.Stop(c)

		if err := gui.OSCommand.Kill(gui.SubProcess); err != nil {
			gui.Log.Error(err)
		}
	}()

	fmt.Fprintf(os.Stdout, "\n%s\n\n", utils.ColoredString("+ "+strings.Join(gui.SubProcess.Args, " "), color.FgBlue))

	if err := gui.SubProcess.Run(); err != nil {
		// not handling the error explicitly because usually we're going to see it
		// in the output anyway
		gui.Log.Error(err)
	}

	gui.SubProcess.Stdin = nil
	gui.SubProcess.Stdout = ioutil.Discard
	gui.SubProcess.Stderr = ioutil.Discard
	gui.SubProcess = nil

	signal.Stop(c)

	if !gui.Config.UserConfig.Gui.ReturnImmediately {
		fmt.Fprintf(os.Stdout, "\n\n%s", utils.ColoredString(gui.Tr.PressEnterToReturn, color.FgGreen))

		// wait for enter press
		if _, err := fmt.Scanln(); err != nil {
			gui.Log.Error(err)
		}
	}

	return nil
}
```

My guess is that everytime that the command that gets returned from ViewLogs gets called, it will run for ever. Meaning that every time you call ViewLogs, you spawn another subprocess. For some reason the stop signal doesn't really stop it. Which I find weird.

Waiting for others observations.

**Comment by keigel2001** [comment]
Can you reproduce it on your system?

**Comment by jesseduffield** [comment]
I can reproduce this error on my end. @glvr182 that code you've linked is specifically for when you press 'm' to view logs as a subprocess, but I think the issue here is when we have a process running whose output is going to the main panel. This is basically what is managed by the `TaskManager` struct in `pkg/tasks/tasks.go`.

I've put up a PR https://github.com/jesseduffield/lazydocker/pull/148 that should fix the issue. It ensures we close the current task when we close lazydocker.

Though I am perplexed as to how the child process can still be hanging around after we close lazydocker. The only reason I imagine that it would is if it had a different process group id to lazydocker. We do this via `PrepareForChildren` in `os.go` for some processes like `docker-compose logs` because that itself spawns child processes so we give them their own group id and then kill the group when we want to stop that process. But we're not doing that with normal container logs. So if anybody has any ideas on how to fix the underlying issue I'd like to know :)

**Comment by glvr182** [comment]
@jesseduffield Good point, I am reading up on childprocesses and stopping them,
I have found this topic, maybe we exit 'too clean'
https://groups.google.com/forum/#!topic/golang-nuts/shST-SDqIp4
