### ISSUE TITLE
Suggestion: self-update

### ISSUE THREAD

**Issue by Suika** [jesseduffield/lazydocker#153]
**Is your feature request related to a problem? Please describe.**
Since this a new project that is rapidly developed and constantly adds new feature,
the repeated updates are becoming slightly more painful to deploy on multiple servers.

**Describe the solution you'd like**
Add a self-update functionality that will pull the latest binary from github/your build source and replace/update existing binary. `lazydocker self-update`

**Describe alternatives you've considered**
A shell script that pulls newest version and replaces the old binary.
But in this case it's already 2 files and they may not work in all environments.

**Additional context**
Another GO project that implemented a self-update feature and can possibly provide code for the update function.
https://github.com/restic/restic/pull/1949

**Comment by mjarkk** [comment]
I'm not sure if this is a good idea,  
If everyone pulled from source this could be totally fine but most users will get it from a package manager.  
When lazydocker would auto update itself it will probably get in conflict with the package because they will have 2 different versions.  
And this will get worse when the package manager has a newer version but the version is older than the latest release thus the user will get downgraded by it's package manager with the problems that might come from that like conflicting configs.  

Also the code is changed every month but the project is stable and most users won't care much about updates unless they know what is added every update and they know what that makes a difference for them.  

If a user really always wants the best version just use:   
```
go get -u github.com/jesseduffield/lazydocker
```

To me this seems like something that only saves time for the package deployed.  
And if that is the case i think most users are fine with waiting a week for a new version of the program.  

But correct me if i'm wrong because what you suggest is likable idea,

**Comment by Suika** [comment]
Sure, I'll take you up on it.

Think of it in this way, packages are prepared and compiled from source for the said distribution.
As a means of better integration into the system. What you are probably talking about are the rolling releases and some bleeding edge user repositories that provide the package.

It is possible to, deactivate the self-update feature via a build flag, which would not bother the packaged versions of the software.

-------

Since this a GO project and the software is statically compiled, it make the portable to a point that if you have single version of it, you might just copy it everywhere from your systems.

But that is beside the point that, it's about people that are downloading the software from here(github).

>Also the code is changed every month but the project is stable and most users won't care much about updates unless they know what is added every update and they know what that makes a difference for them.

> unless they know
bingo, there you have it. it's basically a QOL feature, that makes it easy to update.

https://api.github.com/repos/jesseduffield/lazydocker/releases :
```
113 lazydocker_0.2.4_Linux_arm64.tar.gz
114 lazydocker_0.2.1_Linux_x86_64.tar.gz
139 lazydocker_0.2.1_Darwin_x86_64.tar.gz
386 lazydocker_0.2.5_Linux_x86_64.tar.gz
468 lazydocker_0.7_Linux_x86_64.tar.gz
491 lazydocker_0.5.4_Linux_x86_64.tar.gz
527 lazydocker_0.6.3_Linux_x86_64.tar.gz
682 lazydocker_0.5.4_Darwin_x86_64.tar.gz
698 lazydocker_0.2.5_Darwin_x86_64.tar.gz
971 lazydocker_0.7_Darwin_x86_64.tar.gz
975 lazydocker_0.6.4_Linux_x86_64.tar.gz
1127 lazydocker_0.4_Linux_x86_64.tar.gz
1188 lazydocker_0.6.3_Darwin_x86_64.tar.gz
1234 lazydocker_0.4_Darwin_x86_64.tar.gz
1336 lazydocker_0.2.4_Linux_x86_64.tar.gz
1351 lazydocker_0.2.4_Darwin_x86_64.tar.gz
1468 lazydocker_0.6.4_Darwin_x86_64.tar.gz
1706 lazydocker_0.3_Darwin_x86_64.tar.gz
1914 lazydocker_0.3_Linux_x86_64.tar.gz
3428 lazydocker_0.5.5_Darwin_x86_64.tar.gz
3555 lazydocker_0.5.5_Linux_x86_64.tar.gz
```

You can actually see how often the people visit this repo to download/update the package.
Run: `wget https://api.github.com/repos/jesseduffield/lazydocker/releases -q -O- | jq '.[]["assets"][]|"\(.download_count) \(.name)"' -r`
If you look at it, you can see how often the software and what version is downloaded. It's basically people remembering to check the project for new releases.

--------

> go get -u github.com/jesseduffield/lazydocker

Why thank you for the build environment that is not really needed.

I know what you mean, but it's adding packages, downloading data and other parts and then compiling it.
It works, but do you really want to have that in production?

------

>To me this seems like something that only saves time for the package deployed.
And if that is the case i think most users are fine with waiting a week for a new version of the program.

> saves time for the package deployed

What repo? https://repology.org/project/lazydocker/versions

**Comment by mjarkk** [comment]
> But that is beside the point that, it's about people that are downloading the software from here(github).  

Oww, i thought you also meant the lazydocker packages in the repositories ([here](https://repology.org/project/lazydocker/versions)).  
In that case this makes a lot more sense because this is something frustrating when having binaries from the github release page.  

If it's just that i'm totally fine with this change, this is indeed something nice to have in these blobs.

**Comment by jesseduffield** [comment]
lazygit actually has an update feature in the app. I removed it for lazydocker because I felt it wasn't really an important feature, but it appears I was wrong! I suspect it wouldn't be hard to grab the code from lazygit and port it over to here. Relevant file: https://github.com/jesseduffield/lazygit/blob/master/pkg/updates/updates.go

Worth noting that that supports auto-updates, and its an open question whether we want to support that here or just to support user-initiated updated from within the app

**Comment by Suika** [comment]
If it ain't broke, don't fix it. Auto-updates should be plannable, but not self-executing.
Can be fixed by an alias `alias lazydocker='lazydocker --update' `, since I guess that's what it would basically do if it were implemented as auto-update.
