### ISSUE TITLE
Controlling the sidebar width

### ISSUE THREAD

**Issue by probablykasper** [jesseduffield/lazydocker#216]
The sidebar can often take up more horizontal space than you'd want.

In this example, you can see the sidebar takes up significantly more space than necessary:
![image](https://user-images.githubusercontent.com/11315492/79369125-be988800-7f50-11ea-8303-7992cbeeba5d.png)

In a smaller terminal, you might also want it to take up less space. I would be fine with seeing less of the volume ID:
![image](https://user-images.githubusercontent.com/11315492/79369255-f4d60780-7f50-11ea-8c4a-1758eedd282d.png)

I have three possible suggestions:
- Detect the width of the content of the sidebar panes, and make the width smaller if necessary. Exclude the volumes pane from that calculation (though there could be a setting for this).
- Allow a max width to be set

Then there's also some related things already suggested in #180:
- Collapsible left panel (#180)
- Use keybinds for increasing and decreasing the width

**Comment by msva** [comment]
I'd like to upvote the idea of changing the width of left panel.
Although, in my case, the reason is that names are too long ('cause of Swarm naming scheme) and I don't even see all the things after the names in "Containers" block.

Also, it would be nice to navigate between left blocks not by left/right arrows keys, but with tab. And use horizontal arrows to horizontal scroll of active block's content...

Also, it would be nice to have the ability to manage blocks (hide unneded, and add custom ones, defined in config).

**Comment by jesseduffield** [comment]
This is addressed in https://github.com/jesseduffield/lazydocker/pull/372 with a couple things:
* pressing '+' increases side bar size
* you can configure a default ratio between side bar and main panel with the `gui.sidePanelWidth` config key (default is 0.333)

**Comment by jesseduffield** [comment]
https://github.com/jesseduffield/lazydocker/pull/372 is now in master. Lemme know if you want to re-open.

**Comment by huyz** [comment]
I can see `+` can zoom into the side bar. But is there a way to maximize the Logs view?
