### ISSUE TITLE
Getting unsupported terminal when acessing server via ssh with alacritty

### ISSUE THREAD

**Issue by deadpyxel** [jesseduffield/lazydocker#225]
**Describe the bug**
When accessing a remote server via SSH with alacritty, if I try to start `lazydocker` I get an error message about unsupported terminal. IF I try to run lazydocker on my own machine, using the same terminal, it works fine. If I do the same access using `gnome-terminal` and invoke lazydocker, the application behaves. 

Just to be clear, alacritty is installed in my machine, the other machine is a simple server I acess with SSH.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install alacritty
2. Access another remote host via ssh using alacritty
3. invoke lazydocker
5. Open alacritty in your host
6. invoke lazydocker
7. Application behaves

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Archlinux (My Machine) x64, Debian 9.12 (Remote server)
 - Shell: zsh (Mine), bash (remote server)
 - Lazydocker Version: v0.9, commit 10617da5608990bf4911142745d31566bac6964a
 - The last commit id if you built project from sources (run : ```git rev-parse HEAD```)

**Additional context**
Error message:
```
2020/07/17 09:18:43 An error occurred! Please create an issue at https://github.com/jesseduffield/lazydocker/issues

*errors.errorString termbox: error while reading terminfo data: termbox: unsupported terminal
/home/circleci/project/main.go:88 (0x8a8d69)
/usr/local/go/src/runtime/proc.go:200 (0x42d79c)
/usr/local/go/src/runtime/asm_amd64.s:1337 (0x4585b1)
```

**Comment by tupini07** [comment]
I also use `alacritty` and experience this same issue when trying to use applications on a remote machine. For instance, I get this issue when trying to open `vim` or `less`. What I do to fix this is just set the `TERM` variable in the remote to `xterm` (in bash: `export TERM=xterm`). To prevent having to do this constantly, I set an alias to `TERM=xterm ssh` in my local machine.

I haven't tried with `lazydocker` since I've never needed to execute it in a remote machine, but maybe you try setting the `TERM` variable as mentioned above? At least as a temporary fix.

**Comment by deadpyxel** [comment]
That works very well, thanks. I was not really sure in what was causing this, but since `alacritty` is in beta I didn't know if this issue was in `lazydocker` or in `alacritty`. I'll try to report this on `alacritty`'srepo too. Do you think this is worth a README update to let people know?

**Comment by NurdinDev** [comment]
I'm using Alacritty and Tmux and I have the same problem, I set this line `set -g default-terminal "screen-256color"` in my tmux.conf and it's working

**Comment by jesseduffield** [comment]
This is now resolved on master, closing :)
