### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated!

### ISSUE THREAD

**Issue by studious** [jesseduffield/lazydocker#273]
I'm just reporting this here. Same as lazygit

Cheers

**Comment by den-is** [comment]
Please help brew to stop producing that annoying warning :((((

**Comment by ocsw** [comment]
bump?

**Comment by den-is** [comment]
@jesseduffield is it possible to fix that, that should be taking much time and is not touching actual application's logic and code

**Comment by jesseduffield** [comment]
@den-is apologies I've made the grave error of maintaining two open source repos haha: lazygit certainly gets a lot more love.

As for this issue, it's a result of goreleaser using the deprecated bottling approach. That was fixed in goreleaser back in [october](https://github.com/goreleaser/goreleaser/issues/2595). We always use the latest goreleaser on release, however our CI is currently failing due to some code that windows does not support.

I've got a PR up to address this but will need help from people who use an SSH connection to docker to see if any child zombie processes are left after running lazydocker (or alternatively, if anybody can guide me on setting up docker via SSH on my mac I can test this out myself)

**Comment by omaksi** [comment]
I've just tried installing and I'm actually getting an error for this, and it won't install from your tap.

```Error: Invalid formula: /usr/local/Homebrew/Library/Taps/jesseduffield/homebrew-lazydocker/lazydocker.rb
lazydocker: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the jesseduffield/lazydocker tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/jesseduffield/homebrew-lazydocker/lazydocker.rb:9

Error: Cannot tap jesseduffield/lazydocker: invalid syntax in tap!
```

Installing from core works OK.

**Comment by mark2185** [comment]
I have a `mac` lying around, what do I need to do? Just `brew install lazydocker`?

**Comment by jesseduffield** [comment]
Nice. The core homebrew repo is yet to merge the lazydocker PR but you can test out the tap like so:
```
brew install jesseduffield/lazydocker/lazydocker
```

**Comment by jesseduffield** [comment]
Woohoo! Thanks @mark2185 , let's close this off
