### ISSUE TITLE
[Feature request] Info how to detach from previously attached container

### ISSUE THREAD

**Issue by Mayurifag** [jesseduffield/lazydocker#287]
**Is your feature request related to a problem? Please describe.**
It seems, project has no info or way to detach from container. It's always frustrates me, how am I attaching to container, do things I want to and... How should I quit? Whats the hotkey? Where may I find it? How to google that?

I'm doing `CTRL+C` now, and obviously that stops the container. Now I need to return to lazydocker, restart via `r` the container and, sometimes, I need some time to restore the condition my container was.

Other way is make another tab in terminal. I don't like that, for sure.

**Describe the solution you'd like**
I wish the project's `README.md` to point the hotkey how to detach from container and return to lazydocker. 

Furthermore, there is yet-another solution, which seems more user-and-its-mind-friendly — after attaching to container we should see not only the command `lazydocker` launched to get us to the container (I mean, i.e. `docker attach --sig-proxy=false as1sd12.....adfa30143`), [which seems to be useless by itself as for me] but also the information with hotkey how to exit the container somewhere (near the text with `docker attach ...` we might see `Detach from container: CTRL+D`).

**Comment by milushov** [comment]
Hey I'm wondering the same, any advice would be helpful

**Comment by milushov** [comment]
I found actually https://github.com/jesseduffield/lazydocker/pull/116

There are sequence of hotkeys: `ctrl-p ctrl-q`

**Comment by jesseduffield** [comment]
This would be simply to implement: We would simply need to go to `pkg/gui/subprocess.go` and do the following:
* change the `runCommand` method to accept a string message argument
* add a string message argument to `runSubprocess` and pass it through to `runCommand`
* rename `runSubprocess` to `runSubprocessWithMessage` and then create a new `runSubprocess` method which calls `runSubprocessWithMessage` passing an empty string for the message

Then we would be able to say 'By default, to detach from the container press ctrl-p then ctrl-q' and pass that as the message to `runSubprocessWithMessage` from `handleContainerAttach` in `pkg/gui/containers_panel.go`

I'll chuck a hacktoberfest label on this because it will be an easy issue for anybody to pick up

**Comment by glendsoza** [comment]
Hi, i have created a PR here  to display message as described in the previous comment 

Please review -> https://github.com/jesseduffield/lazydocker/pull/411
