### ISSUE TITLE
Service stop buttons

### ISSUE THREAD

**Issue by MisterGlass** [jesseduffield/lazydocker#73]
It would be great if there were buttons allowing me to stop/kill containers right in the lazy docker UI, rather than pulling up another CLI window & entering the stop command manually.

**Comment by mjarkk** [comment]
Have you read: https://github.com/jesseduffield/lazydocker/blob/master/docs/keybindings/Keybindings_en.md  
> `d`: remove
> `s`: stop

**Comment by MisterGlass** [comment]
That is good to know! I'll definitely start using those shortcuts, though I find buttons more friendly.

Not all users are using compose, but maybe a kill all button would be better in that case.

**Comment by jesseduffield** [comment]
@MisterGlass I'm aware that these commands can be used to stop/remove all containers:
```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
```

It sounds like what we might want is to make shift+S run that first command, and shift+d run the second one. We'd need to move the prune command to 'p' but that's fine. Or maybe it's not because we might want to have docker push and docker pull reserved for p to bring it inline with lazygit's commands. Maybe we should just chuck all three options into a menu. What are our thoughts?

**Comment by MisterGlass** [comment]
@jesseduffield I would prefer an action menu or something along those lines to keyboard shortcuts. I ran out of headspace to memorize more shortcuts years ago ;)

**Comment by jesseduffield** [comment]
I believe this is now implemented, so I'm closing. If I've misunderstood, let me know and we can reopen
