### ISSUE TITLE
Can not interact tab in hyper term

### ISSUE THREAD

**Issue by tuantmtb** [jesseduffield/lazydocker#89]
**Describe the bug**
When I open `lazydocker` in Hyper.app (OSX). I could not switch tab `Stats`, or `Config`
But I open Terminal.app (default), It work.
**Screenshots**
![image](https://user-images.githubusercontent.com/9003486/60637338-43903600-9e44-11e9-90ce-017e5cb749c6.png)

**Desktop (please complete the following information):**
 - OS: OSX

Hope `Lazydocker` update soon.

**Comment by IanSchweer** [comment]
Same bug for me

**Comment by ilaskaev** [comment]
Keybindings also work for me, though not clicking on hyper term. 

OS: Windows

**Comment by jesseduffield** [comment]
I actually came across this issue when using lazygit with hyper. The mouse clicks as far as I can tell are just whack: It thinks you're clicking below where the actual cursor is. You can verify this by trying to click on any of the items in the side panels. So it just happens that you can't click high enough for the click to be registered against the tabs because they're on the first row.

If there are other terminal UI's in hyper that have mouse support, I'm interested to know if they exhibit the same problem. If so, it's an issue with hyper. If not, it's an issue with the gocui library: https://github.com/awesome-gocui/gocui

If you can find another app made with gocui that supports mouse events and doesn't have this misalignment issue, then I'm happy to reopen this issue. Otherwise, I'm closing :)
